export declare const squidMainLink = "https://www.squidrouter.com/";
export declare const squidDocLink = "https://docs.widget.squidrouter.com/";
export declare const squidApiBaseUrl = "https://dev.api.squidrouter.com";
export declare const squidDiscordLink = "https://discord.gg/squidrouter";
export declare const squidZenDeskSupportLink = "https://squidsupport.zendesk.com/hc/en-us/requests/new";
export declare const squidHelpLink: string;
export declare const squidInfiniteApprovalLink: string;
export declare const squidSlippageToleranceLink: string;
export declare const squidAxlUSDCWarningLink: string;
export declare const squidTrackingDataUnavailableLink: string;
export declare const squidGasFeesRefundLink: string;
export declare const axelarTokenDataUrl = "https://axelar-mainnet.s3.us-east-2.amazonaws.com/mainnet-config.json";
export declare const axelarMainLink = "https://axelar.network/";
export declare const axelarPoweredByLink = "https://axelar.network/?utm_source=dynamic&utm_medium=referral&utm_campaign=squidrouter-widget";
