export declare const walletIcons: {
    binance: any;
    metamask: any;
    keplr: any;
    walletConnect: any;
    coinbase: any;
    brave: any;
    leap: any;
    cosmostation: any;
    xdefi: any;
    bitkeep: any;
    trustwallet: any;
    fetchai: any;
    coin98: any;
    rabby: any;
    soul: any;
    okx: any;
    injected: any;
    zerion: any;
};
