export declare enum DexName {
    UNISWAP_V2 = "UniswapV2",
    UNISWAP_V3 = "UniswapV3",
    UBESWAP = "Ubeswap",
    SPOOKYSWAP = "Spookyswap",
    SUSHISWAP = "Sushiswap",
    STELLASWAP = "Stellaswap",
    PANGOLIN = "Pangolin",
    CURVE_V2 = "Curve_v2",
    CURVE_V2_CELO = "Curve_v2_celo",
    ELLIPSIS = "Ellipsis",
    QUICKSWAP = "Quickswap",
    STELLASWAP_SADDLE = "Stellaswap_Saddle",
    QUICKSWAP_V3 = "Quickswap_v3",
    PANCAKESWAP = "Pancakeswap",
    PANCAKESWAP_V3 = "Pancakeswap_v3",
    PANCAKESWAP_STABLE = "Pancakeswap_stable",
    TRADERJOE = "TraderJoe",
    TRIDENT = "Trident",
    PLATYPUS = "Platypus",
    WOMBAT = "Wombat",
    ZYBERSWAP = "Zyberswap",
    KYBERSWAP = "KyberSwap",
    KYBERSWAP_AGGREGATOR = "KyberSwap_Aggregator",
    GMX = "GMX",
    APESWAP = "Apeswap",
    OPENOCEAN = "OpenOcean"
}
